### ISSUE TITLE
Deployed version not responding

### ISSUE THREAD

**Issue by axeberg** [chas-academy/07-recipe-app-backend-okan-s#1]
@okan-s I can't grade your u06 or this one with a deployed backend that works. Ping me back when you've got it working and I'll take a look.

**Comment by okasi** [comment]
Works fine for me? Maybe Binero servers had problems during the moment you visited the page?
http://recipe.okasi.me/

**Comment by axeberg** [comment]
Still not possible to register though.

On 26 March 2019 at 08:28:51, Okan S. (notifications@github.com) wrote:

Works fine for me? Maybe Binero servers had problems during the moment you
visited the page?
http://recipe.okasi.me/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chas-academy/07-recipe-app-backend-okan-s/issues/1#issuecomment-476506231>,
or mute the thread

**Comment by axeberg** [comment]
@okan-s See above

**Comment by axeberg** [comment]
Nevermind, apparently my email had already been registered.

**Comment by axeberg** [comment]
Done graded.
